const TEMPLATE = `
##########################
### IDE specific files ###
##########################

# Ignore files generated by JetBrains IDEs
.idea
# Ignore files generated by VSCode
.vscode

###########################
### Deno specific files ###
###########################

# Ignore deno cache
vendor
# Ignore deno coverage files
coverage
`

type writeTextFileFn = (path: string, text: string) => Promise<void>
type Injects = {
  write: writeTextFileFn
}

export async function createGitIgnore(dryRun: boolean = false, injects: Injects = {
  write: Deno.writeTextFile
}): Promise<string|void> {

  if(dryRun){
    return Promise.resolve(TEMPLATE)
  }

  await injects.write('.gitignore', TEMPLATE)
}