// deno-lint-ignore-file require-await
import { assertEquals } from '@std/assert'
import { createGitIgnore } from '../../src/helpers/create-gitignore.ts'

// Extract the TEMPLATE so we can test it precisely
const TEMPLATE = `
##########################
### IDE specific files ###
##########################

# Ignore files generated by JetBrains IDEs
.idea
# Ignore files generated by VSCode
.vscode

###########################
### Deno specific files ###
###########################

# Ignore deno cache
vendor
# Ignore deno coverage files
coverage
`

Deno.test('createGitIgnore returns template in dry-run mode', async () => {
  const result = await createGitIgnore(true)
  assertEquals(result, TEMPLATE)
})

Deno.test('createGitIgnore writes .gitignore file when not dry-run', async () => {
  let writtenPath = ''
  let writtenText = ''

  const write = async (path: string, text: string) => {
    writtenPath = path
    writtenText = text
  }

  const result = await createGitIgnore(false, { write })
  assertEquals(result, undefined)
  assertEquals(writtenPath, '.gitignore')
  assertEquals(writtenText, TEMPLATE)
})
